= V4L2-Utilities

== Packages and Libraries:
[cols="1,3", options="header"]
|===
| Package Name | Description

| v4l-utils
| Provides command-line tools like `v4l2-ctl` and `qv4l2` for managing V4L2 devices.

| libv4l
| User-space library offering APIs for video format conversion and device control.

| v4l2loopback
| Enables creation of virtual video devices for simulating or redirecting video streams.

| media-ctl
| Command-line tool for configuring complex video pipelines using the Media Controller API.

| uvcdynctrl
| Utility for accessing and modifying extended controls on UVC-compliant webcams.
|===

== Installing the Utilities:

To include all the packages into our image we need to modify *local.conf* or image *.bb* file

|===
|"IMAGE_INSTALL:append = "v4l-utils libv4l media-ctl v4l2loopback uvcdynctrl "
|===

Then build the image and flash it on the verdin board.

NOTE=>By default it is installed in multimedia image.

== Checking the device availability & its capability

* Boot and Verify

+
[source,shell]
----
$ v4l2-ctl --version
$ media-ctl -h
----

* Check video device nodes

+
[source,shell]
----
$ ls /dev/video*
----

+
Typical output:

+
[source,txt]
----
/dev/video0, /dev/video1 → V4L2 capture devices
/dev/media0, /dev/media1 → Media controller interface (for CSI/MIPI cameras)
----

* Identify devices with v4l2-ctl

+
`v4l2-ctl --list-devices`

*  Inspect Media Pipeline (For CSI/MIPI)

+
`media-ctl -p`

+
Outputs:

** Entities (camera sensor, CSI, MIPI, ISP)
** Links (between pipeline components)
** Pads and formats

== Using v4l2 and qv4l2

* Common v4l2 commands 

+
A powerful CLI utility to interact with V4L2 devices. Ideal for scripting, debugging, and headless systems.

+
[cols="1,3", options="header"]
|===
| Purpose | Command

| List video devices                    
| `v4l2-ctl --list-devices`

| Show device info                      
| `v4l2-ctl -d /dev/video2 --all`

| List supported formats                
| `v4l2-ctl -d /dev/video2 --list-formats-ext`

| Set resolution & pixel format         
| `v4l2-ctl -d /dev/video2 --set-fmt-video=width=1280,height=720,pixelformat=MJPG`

| Set camera control (e.g., brightness) 
| `v4l2-ctl -d /dev/video2 --set-ctrl brightness=64`

| Capture one frame to file             
| `v4l2-ctl -d /dev/video2 --stream-mmap --stream-count=1 --stream-to=frame.raw`

|===

=== Commands and its output examples :

. $ v4l2-ctl --list-devices
+
[source,shell]
----
vsi_v4l2dec (platform:vsi_v4l2dec):
        /dev/video1

vsi_v4l2enc (platform:vsi_v4l2enc):
        /dev/video0

USB Camera: USB Camera (usb-xhci-hcd.1.auto-1.2):
        /dev/video2
        /dev/video3
        /dev/media0
----

. $  v4l2-ctl -d /dev/video2 
+
[source,shell]
----            
Driver Info:
        Driver name      : uvcvideo
        Card type        : USB Camera: USB Camera
        Bus info         : usb-xhci-hcd.1.auto-1.2
        Driver version   : 6.6.84
        Capabilities     : 0x84a00001
                Video Capture
                Metadata Capture
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x04200001
                Video Capture
                Streaming
                Extended Pix Format
Media Driver Info:
        Driver name      : uvcvideo
        Model            : USB Camera: USB Camera
        Serial           : SN0001
        Bus info         : usb-xhci-hcd.1.auto-1.2
        Media version    : 6.6.84
        Hardware revision: 0x00000100 (256)
        Driver version   : 6.6.84
Interface Info:
        ID               : 0x03000002
        Type             : V4L Video
Entity Info:
        ID               : 0x00000001 (1)
        Name             : USB Camera: USB Camera
        Function         : V4L2 I/O
        Flags            : default
        Pad 0x01000007   : 0: Sink
          Link 0x02000010: from remote pad 0x100000a of entity 'Extension 3' (Video Pixel Formatter): Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
        Width/Height      : 1280/720
        Pixel Format      : 'MJPG' (Motion-JPEG)
        Field             : None
        Bytes per Line    : 0
        Size Image        : 1843789
        Colorspace        : sRGB
        Transfer Function : Default (maps to sRGB)
        YCbCr/HSV Encoding: Default (maps to ITU-R 601)
        Quantization      : Default (maps to Full Range)
        Flags             : 
Crop Capability Video Capture:
        Bounds      : Left 0, Top 0, Width 1280, Height 720
        Default     : Left 0, Top 0, Width 1280, Height 720
        Pixel Aspect: 1/1
Selection Video Capture: crop_default, Left 0, Top 0, Width 1280, Height 720, Flags: 
Selection Video Capture: crop_bounds, Left 0, Top 0, Width 1280, Height 720, Flags: 
Streaming Parameters Video Capture:
        Capabilities     : timeperframe
        Frames per second: 25.000 (25/1)
        Read buffers     : 0

User Controls

                     brightness 0x00980900 (int)    : min=-64 max=64 step=1 default=0 value=0
                       contrast 0x00980901 (int)    : min=0 max=64 step=1 default=32 value=32
                     saturation 0x00980902 (int)    : min=0 max=128 step=1 default=67 value=67
                            hue 0x00980903 (int)    : min=-40 max=40 step=1 default=0 value=0
        white_balance_automatic 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=72 max=500 step=1 default=100 value=100
                           gain 0x00980913 (int)    : min=0 max=100 step=1 default=0 value=0
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=1 value=1 (50 Hz)
                                0: Disabled
                                1: 50 Hz
                                2: 60 Hz
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=1 default=4600 value=4600 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=6 step=1 default=3 value=3
         backlight_compensation 0x0098091c (int)    : min=0 max=2 step=1 default=1 value=1

Camera Controls

                  auto_exposure 0x009a0901 (menu)   : min=0 max=3 default=3 value=3 (Aperture Priority Mode)
                                1: Manual Mode
                                3: Aperture Priority Mode
         exposure_time_absolute 0x009a0902 (int)    : min=1 max=5000 step=1 default=157 value=157 flags=inactive
     exposure_dynamic_framerate 0x009a0903 (bool)   : default=0 value=1
----

. $ v4l2-ctl -d /dev/video2 --list-formats-ext
+
[source,shell]
----                                                                                                                      
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'MJPG' (Motion-JPEG, compressed)
                Size: Discrete 1280x720
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
        [1]: 'YUYV' (YUYV 4:2:2)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
----
. $ `v4l2-ctl -d /dev/video2 --set-fmt-video=width=1280,height=720,pixelformat=MJPG` 
. we need to check whether check format is successfull or not, So `$ v4l2-ctl -d /dev/video2 --get-fmt-video`
+
[source,shell]
----
Format Video Capture:
        Width/Height      : 1280/720
        Pixel Format      : 'MJPG' (Motion-JPEG)
        Field             : None
        Bytes per Line    : 0
        Size Image        : 1843789
        Colorspace        : sRGB
        Transfer Function : Default (maps to sRGB)
        YCbCr/HSV Encoding: Default (maps to ITU-R 601)
        Quantization      : Default (maps to Full Range)
        Flags             : 
----

. `$ v4l2-ctl -d /dev/video2 --set-ctrl brightness=64`
. To confirm the brightness value :- `$ v4l2-ctl -d /dev/video2 --get-ctrl brightness`
+
[source,shell]
----
brightness: 64
----

. Now we all set to capture, So `$ v4l2-ctl -d /dev/video2 --stream-mmap --stream-count=1 --stream-to=frame.raw`
+
[source,shell]
----
ls -l frame.raw 
-rw-r--r-- 1 root root 71808 Mar  6 06:20 frame.raw
----

* it will create frame.raw captured file 
+
image::images\frame.raw[Camera Flow Diagram, width=600, height=300]

=== qv4l2-Qt-based GUI Tool
A graphical utility for easy testing and interaction with V4L2 devices (used when GUI is available).

`qv4l2`

Use on development boards with GUI-enabled Yocto image

*Features of qv4l2*

. Live camera preview
. Format selection (resolution, pixel format)
. Real-time adjustment of camera controls (e.g., focus, contrast)
. Useful for debugging without writing code